### ISSUE TITLE
separate crate(s) for ambient authority

### ISSUE THREAD

**Issue by dckc** [bytecodealliance/cap-std#129]
briefly: the way I recommend applying ocap discipline in rust is:
  - only the main bin crate gets access to ambient authority
  - lib crates do not

so in crates such as the rand crate, separate the interfaces for accessing the thread RNG and such to their own crate, for use from the main bin crate.

see also https://github.com/dckc/rust/issues/2
https://github.com/dckc/rust-sqlite3/blob/master/src/access/mod.rs

**Comment by sunfishcode** [comment]
We currently indicate ambient authorities with `unsafe`. For example cap-rand's `thread_rng` function is `unsafe`. This tends to make usage of ambient APIs stand out -- they must be wrapped in `unsafe { }` blocks. And it gives users the option of using `#![forbid(unsafe_code)]` in their crates to ensure that no such APIs are used. So the question is, is that sufficient, or would there be a benefit to splitting things into separate crates?

Alternatively, would the `tag_safe` idea obviate this entirely?

In some cases, splitting ambient-authority functions into separate crates would make the code more complex. For example `thread_rng` could no longer directly initialize `CapRng`'s `inner` field from a different crate, so we'd need extend `CapRng`'s public API to allow other crates to initialize it. We can do things like that, but I'd like to understand the tradeoffs before we do.

**Comment by dckc** [comment]
Yes, I saw the use of `unsafe` to flag ambient authority; that's what prompted this issue. (silly me neglected to say so in the first place...)

`open("/etc/motd")` is not `unsafe` in the rust sense, and saying it is seems like asking for trouble.

I'll have to look more closely at the cross-crate complexity... what you describe reminds me of attempts to tame Java objects by just casting away certain methods on certain objects. But the methods were still there and the object could be cast back to expose them. (Darn; can't find it in the [Joe-E](https://www.ndss-symposium.org/wp-content/uploads/2017/09/met.pdf) nor [DarpaBrowser](http://www.combex.com/papers/darpa-report/darpaBrowserFinalReport.pdf) paper). That is: yes, it can be more work to pass authority around explicitly, but that's the price of ocap discipline (and the cost is will worth it, quite often, in my experience).

> Alternatively, would the `tag_safe` idea obviate this entirely?

That does seem entirely possible, yes.

**Comment by erights** [comment]
> But the methods were still there and the object could be cast back to expose them. (Darn; can't find it in the Joe-E nor DarpaBrowser paper). 

The taming mechanisms (and taming decisions) of both E and Joe-E had a lot of problems. But we got this much right. When taming censored a Java method, no simple trick from E or Joe-E would route around the taming.

**Comment by sunfishcode** [comment]
cap-std's use of unsafe here is inspired by Rust's own standard library: [`File::from_raw_fd`](https://doc.rust-lang.org/stable/std/fs/struct.File.html#method.from_raw_fd) is unsafe, and not because of memory safety&mdash;copying file descriptors and operating on them independently has well-defined and memory-safe behavior in Posix-ish platforms&mdash;but because doing so could lead to corrupted I/O in some circumstances. In effect, there's a convention of "I/O safety" in the standard library. cap-std here is using a convention of "capability safety".

`unsafe` seems to fit the need well, and in practice so far hasn't been confusing, because code working with `cap-std` doesn't tend to be doing memory-`unsafe` or even I/O-`unsafe` things. But if there are practical problems with using `unsafe` in this way, I'm certainly open to considering other mechanisms.

The `tag_safe` idea looks promising, and it may make sense to do both: the `unsafe` convention to help all users use cap-std's own API correctly, and `tag_safe` for people willing to install a rustc plugin to get more comprehensive validation. Does that sound like a good balance?

**Comment by dckc** [comment]
> `File::from_raw_fd` is unsafe ... because doing so could lead to corrupted I/O in some circumstances.

TIL. Thanks.

> ... Does that sound like a good balance?

yes.

**Comment by sunfishcode** [comment]
Cool. I'll close this issue then; feel free to reopen or file new issues if there's anything else to add here!
