### ISSUE TITLE
tag_safe custom_attribute for ocap discipline

### ISSUE THREAD

**Issue by dckc** [bytecodealliance/cap-std#130]
Feel free to close this as out of scope, but the idea is:

1. tag functions that are designed to follow ocap discipline:
```rust
#[tagged_safe(ocap="tagsafe_std_ocap.txt")]
extern crate std as _std;

#[tag_safe(ocap)]
fn cap_main<W>(out: &mut W) -> io::Result<()>
```

2. tag functions that use ambient authority as unsafe w.r.t. ocap discipline. The `tagsafe_std_ocap.txt` file db would express the equivalent of:

```rust
#[tag_unsafe(ocap)]
use std::fs::File::open;
```

3. Use the tag_safe linter to go BZZZT if an ocap safe function calls, directly or indirectly, an ocap unsafe function.

refs from around Nov 2016:
https://github.com/thepowersgang/tag_safe/issues/1
https://github.com/dckc/larust-tame
https://github.com/dckc/rust/issues/2#issuecomment-262626680

**Comment by sunfishcode** [comment]
I'm not familiar with `tag_safe` or the rustc plugin system, but this sounds like something interesting to pursue. Would you be interested in putting together a small version of this, that just marks a small number of functions, to show how it work work?

**Comment by dckc** [comment]
I'm interested, yes; whether I'm available is another question. :-/

Here's hoping.

**Comment by sunfishcode** [comment]
It seems the `#![plugin]` mechanism that `tag_safe` is built on is [deprecated](https://github.com/thepowersgang/tag_safe/commit/e4a3bf5ea59c0d9ad6d32978d1174e451ac6e5be).

[cargo-geiger](https://github.com/rust-secure-code/cargo-geiger) is a project that similarly builds a custom static analysis, but uses `syn` rather than being a rustc plugin, which may be something to look into.

And on a related note, I posted [here](https://internals.rust-lang.org/t/deprecate-std-paths-aliases-of-std-fs-functions/13747) about a possible change to Rust's `std` which would help distinguish the parts of the API that use ambient filesystem authorities from the parts that don't.

**Comment by sunfishcode** [comment]
With the switch to the `ambient-authority` crate to model ambient authority, another option is to use clippy. A clippy config file for scanning for ambient_authority() or any of the known functions in std, tempfile, rand, directories_next, or fs_set_times, is here:

https://github.com/sunfishcode/ambient-authority/blob/main/clippy.toml

**Comment by dckc** [comment]
fantastic!
