### ISSUE TITLE
Confusing `path::Path` documentation

### ISSUE THREAD

**Issue by rvolosatovs** [bytecodealliance/cap-std#254]
In latest released version of `cap-async-std` (`0.24.4` at the time of writing)

`canonicalize` method is defined on `path::Path`: https://docs.rs/cap-async-std/latest/cap_async_std/path/struct.Path.html#method.canonicalize

The documentation states that it is an alias for `fs::canonicalize`, however the link in the documentation is broken, since `fs::canonicalize` does not exist and (righfully so) instead is defined on `fs::Dir` https://docs.rs/cap-async-std/latest/cap_async_std/fs/struct.Dir.html#method.canonicalize

On further investigation, I realized that `path` module is re-exported from `async-std` https://github.com/bytecodealliance/cap-std/blob/2636733c047cda304bc53123dff9ca56a953510e/cap-async-std/src/lib.rs#L46 and it seems to be caused by #88 

I understand that the suggested approach is to configure a custom linter with a list of disallowed methods to prevent usage of these. However, the documentation is confusing, references are broken and it's very easy to make a mistake for new users.

If it's not desired to maintain a custom Path type implementation, is there a reason `cap-async-std` crate has to re-export the `path` module at all?

**Comment by sunfishcode** [comment]
The reason for having a path re-export, especially in cap-async-std's case, is to make it easy for users to use the same `Path` type that cap-async-std itself is using, without having to depend on the precise version async-std directly themselves. That said, I agree it's confusing.

One option would be to re-export all of `async_std` instead; I've now implemented this in #255. This is a little untidy, because cap-async-std users should generally avoid using async-std directly, but perhaps it's not worth worrying about. Users of the clippy lint still get warned if any of the ambient-authority functions are invoked.
