### ISSUE TITLE
cap-primitives no longer builds on Nightly for Windows

### ISSUE THREAD

**Issue by repi** [bytecodealliance/cap-std#270]
Not sure when Nightly introduced a change that broke the compilation of `cap-primtives` here, I'm on latest from today `cargo 1.64.0-nightly (85b500cca 2022-07-24)`.

latest stable (1.62) and beta (1.63.0-beta.7) works fine.

this is the error one runs into when building with Nightly:

```
error[E0277]: the trait bound `file_type::FileType: std::sealed::Sealed` is not satisfied
   --> cap-primitives\src\fs\file_type.rs:134:6
    |
134 | impl std::os::windows::fs::FileTypeExt for FileType {
    |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::sealed::Sealed` is not implemented for `file_type::FileType`
    |
    = help: the following other types implement trait `std::sealed::Sealed`:
              Child
              Command
              ExitCode
              ExitStatus
              ExitStatusError
              OsStr
              OsString
              Simd<f32, N>
            and 2 others
note: required by a bound in `std::os::windows::fs::FileTypeExt`
```

Repro:
- `cargo +nightly build --workspace`

**Comment by ChrisDenton** [comment]
`FileTypeExt` was stabilized and sealed in https://github.com/rust-lang/rust/pull/98583

**Comment by philpax** [comment]
I can confirm that #271 resolves the compilation issue for me:
```
[patch.crates-io]
cap-primitives = { git = "https://github.com/bytecodealliance/cap-std.git", branch = "sunfishcode/file-type-ext" }
```

**Comment by philpax** [comment]
Bah, caveat - the patch + wasmtime 0.39.1 works on Windows if you _just_ patch `cap-primitives`, but fails on macOS due to `cap-fs-ext` expecting the new traits. Bringing in `cap-fs-ext` as well results in build errors from `wasi-cap-std-sync` (part of `wasmtime`):

```
error[E0599]: no method named `open_dir_nofollow` found for struct `cap_std::fs::Dir` in the current scope
  --> .cargo\registry\src\github.com-1ecc6299db9ec823\wasi-cap-std-sync-0.39.1\src\dir.rs:87:20
   |
87 |             self.0.open_dir_nofollow(Path::new(path))?
   |                    ^^^^^^^^^^^^^^^^^ method not found in `cap_std::fs::Dir`

error[E0599]: no method named `full_metadata` found for struct `cap_std::fs::DirEntry` in the current scope
   --> .cargo\registry\src\github.com-1ecc6299db9ec823\wasi-cap-std-sync-0.39.1\src\dir.rs:160:34
    |
160 |                 let meta = entry.full_metadata()?;
    |                                  ^^^^^^^^^^^^^

etc
```

So not quite a drop-in solution yet for those using wasmtime 0.39.1 + wasmtime-wasi on a nightly from the last two weeks, but getting there. I think it should be possible for me to fork `wasmtime` and make the relevant patches there, and that should hopefully get me across the line.

**Comment by pinkforest** [comment]
This is broken in 0.64.0 due to the Sealed FileTypeExt for us.. I found the hard way

We are using `wasi-common`: https://github.com/lunatic-solutions/lunatic/issues/136 but it doesn't have point release

I ended up wandering into std :hole: :rabbit2: first: https://github.com/rust-lang/rust/issues/102260

Is it possible to get a point release in wasi-common that gets cap-std 0.26 ?
```
│   │   │   ├── wasi-common v0.40.0
│   │   │   │   ├── cap-rand v0.25.2
│   │   │   │   ├── cap-std v0.25.2
│   │   │   │   │   ├── cap-primitives v0.25.2
```

**Comment by pinkforest** [comment]
btw - Can we pin this issue in the Issues ? I suspect many people are going to wander around in here ? Cheers

**Comment by pinkforest** [comment]
Okay.. the patch works in Windows now but it in turn broke least in all unix due to std stabilised in 1.64.0 ?

This happens for me: https://github.com/bytecodealliance/wasmtime/issues/4936#issuecomment-1257183650

help: the trait `std::os::unix::fs::FileTypeExt` is implemented for `std::fs::FileType`
help: the trait `std::os::unix::fs::FileTypeExt` is implemented for `std::fs::FileType`
help: the trait `std::os::unix::fs::FileTypeExt` is implemented for `std::fs::FileType`
help: the trait `std::os::unix::fs::FileTypeExt` is implemented for `std::fs::FileType`

**Comment by sunfishcode** [comment]
It doesn't break unix. The problem in that issue is that there's a mix of both 0.25.5 and 0.25.2.

**Comment by pinkforest** [comment]
Hmm yeah this is why I hate patching as the lock can be unstable and the patch-branch essentially has to have matching version

Can we do recursive point-release proper for 0.40 users to fix this ?

**Comment by sunfishcode** [comment]
If it's possible to reproduce a problem using unpatched wasi-common 0.40 and Rust stable, it may make sense to consider a point release.

**Comment by pinkforest** [comment]
If it's not indeed in 1.64 yet this willl be most probably end up 1.65 stable given the issue was stabilised.. 

I traced down the exact changes in std and the intent here was to stabilise it via windows_file_type_ext: https://github.com/rust-lang/rust/issues/102260

I'll check the release and see if libs are going to hold it or revert it...

**Comment by pinkforest** [comment]
The stabilisation happened here: https://github.com/rust-lang/rust/pull/98583/files which contained the Sealed error

It should re-produce in 1.64 going by that in 0.40 without the patch to deal with the Sealed change that came along ....

Not sure why it is not re-producing ?
